### ISSUE TITLE
PHP 7.4?

### ISSUE THREAD

**Issue by sikhlana** [WyriHaximusNet/docker-php#51]
Any idea when PHP 7.4 will be added to the docker image?

**Comment by WyriHaximus** [comment]
Working on it at #38, there is one issue that needs to be resolved and that's https://github.com/BitOne/php-meminfo/pull/97 . The extension compiles and installs but on use it segfaults massively. Added tests for that #40. 

There are two things I can do, ship it with a broken `ext-meminfo` on 7.4, or drop `ext-meminfo` temporary, or try to only shit `ext-meminfo` on 7.3. The latter has my preference but I rather see it fixed.

**Comment by sikhlana** [comment]
Ahh I see.

**Comment by WyriHaximus** [comment]
No problem, going to try and not shit it with `ext-meminfo` on 7.4 today. Subscribe to #46 for updates on it's release

**Comment by WyriHaximus** [comment]
@sikhlana FYI the PHP 7.4 image is available since earlier today, did end up leaving `ext-meminfo` out of it for now

**Comment by sikhlana** [comment]
Great. Thanks!
